# -*- coding: utf-8 -*-
"""roll_the_dye.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OV18qBEgbQDECr1kWULkHRS4MG9wk2fH
"""

import random

def ask_for_int(prompt, low, high):
    while True:
        try:
            value = int(input(prompt))
            if value < low or value > high:
                print(f"Please enter a number between {low} and {high}.")
            else:
                return value
        except ValueError:
            print("Invalid input. Please enter an integer.")

def roll_many():
    rolls = ask_for_int(
        "How many times would you like to roll the die? ",
        1,
        1_000_000
    )
    for _ in range(rolls):
        result = random.randint(1, 6)
        print("You rolled:", result)

def roll_6000():
    counters = [0, 0, 0, 0, 0, 0]

    for _ in range(6000):
        roll = random.randint(1, 6)
        counters[roll - 1] += 1

    print("\n--- 6000 Roll Simulation Results ---")
    for i in range(6):
        total = counters[i]
        percent = (total / 6000) * 100
        print(f"Side {i + 1} was rolled {total} times")
        print(f"Side {i + 1} was rolled {percent:.2f}% of the time\n")

roll_many()
roll_6000()