# -*- coding: utf-8 -*-
"""RPS1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujtkWEUA6mIwYg194dNjcCjGSoeQYZu3
"""

def ask_for(data_type, low, high):
  while True:
    try:
      X = float(input(prompt))
      if X < low or X > high:
        print('Must enter value between', low, 'and', high)
      else:
        return X
    except:
      print('Invalid value, try again')

import random
tie = 'It is a tie'
lose = 'You lose!'
won = 'You won!'

def ask_for(data_type, prompt, low, high):
  while True:
    try:
      X = data_type(input(prompt))
      if X < low or X > high:
        print('Must enter value between', low, 'and', high)
      else:
        return X
    except:
      print('Invalid value, try again')

# step 1 - ask user for their choice
prompt = 'Enter 1 for rock, 2 for paper 3 for scissors: '
user = ask_for(int, prompt, 1, 3)

# step 2 - print what the user chose
if user == 1:
  print('You chose rock')
elif user == 2:
  print('You chose paper')
elif user == 3:
  print('You chose scissors')

# step 3 - ask the computer for its choice
comp = random.randint(1,3)

if comp == 1:
  print('Computer chose rock')
elif comp == 2:
  print('Computer chose paper')
else:
  print('Computer chose scissors')

# step 4 - print the outcome
if user == 1 and comp == 1:
  print(tie)
elif user == 1 and comp == 2:
  print(lose)
elif user == 1 and comp == 3:
  print(win)
elif user == 2 and comp == 1:
  print(win)
elif user == 2 and comp == 2:
  print(tie)
elif user == 2 and comp == 3:
  print(lose)
elif user == 3 and comp == 1:
  print(lose)
elif user == 3 and comp == 2:
  print(win)
elif user == 3 and comp == 3:
  print(tie)