# -*- coding: utf-8 -*-
"""RPSLS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m0tOLQ0RH-w2zbKTzaTwrTww8LapdAhL
"""

import random

tie = 'It is a tie'
lose = 'You lose!'
win = 'You won!'

def ask_for(data_type, prompt, low, high):
  while True:
    try:
      X = data_type(input(prompt))
      if X < low or X > high:
        print('Must enter value between', low, 'and', high)
      else:
        return X
    except:
      print('Invalid value, try again')

choices = ('rock', 'paper', 'scissors', 'lizard', 'spock')

outcomes = (
            (tie,  lose, win,  win,  lose),
            (win,  tie,  lose, lose, win),
            (lose, win,  tie,  win,  lose),
            (lose, win,  lose, tie,  win),
            (win,  lose, win,  lose, tie)
           )

user_wins = 0
comp_wins = 0

print('First to 3 wins')

# endless loop
while True:

  # step 1 - ask user for their choice
  prompt = 'Enter 1 for rock, 2 for paper, 3 for scissors, 4 for lizard, 5 for spock: '
  user = ask_for(int, prompt, 1, 5)

  # step 2 - print what the user chose
  print('You chose', choices[user - 1])

  # step 3 - ask the computer for its choice
  comp = random.randint(1,5)
  print('Computer chose', choices[comp - 1])

  # step 4 - print the outcome
  result = outcomes[user - 1][comp - 1]
  print(result)

  # update scores
  if result == win:
    user_wins += 1
  elif result == lose:
    comp_wins += 1

  print('You:', user_wins, 'Computer:', comp_wins)

  # stop when a player wins 3 times
  if user_wins == 3 or comp_wins == 3:
    break